include:
  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right

  - board: nice_nano_v2
    shield: cnano_dongle rgbled_adapter
  - board: nice_nano_v2
    shield: cnano_left
  - board: nice_nano_v2
    shield: cnano_right
