include:
  - board: nice_nano_v2
    shield: charybdis_left
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: charybdis_right

  - board: nice_nano_v2
    shield: cnano_dongle dongle_display
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: cnano_left
  - board: nice_nano_v2
    shield: cnano_right
